env:
  browser: true
  commonjs: true
  es2021: true
extends: google
overrides: [
]
ignorePatterns: ['dist/*', 'docs/*']
parserOptions:
  ecmaVersion: latest
rules: {
  max-len: ["warn", { "code": 140 }]
}
