name: integration-testing
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  discussions: write
  pull-requests: write

jobs:
  generate_failed_job_logs_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create_log_file
        run: |
          cat ./tests/ressources/file_server.log
          exit 1
  generate_failed_job_logs_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create_log_file
        run: |
          cat ./tests/ressources/file_server.log
          exit 1
  analyse_logs_from_previous_steps:
    runs-on: ubuntu-latest
    needs: [generate_failed_job_logs_1, generate_failed_job_logs_2]
    if: ${{ always() }}
    steps:
      - name: analyse_logs_from_previous_steps
        id: analyse_logs_from_previous_steps
        if: always()
        uses: Superbasil3/build-failure-analyser-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          regexes-file-location: https://raw.githubusercontent.com/Superbasil3/build-failure-analyser-action/main/tests/build-failure-analyzer-causes.json
  analyse_logs_from_folder:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - name: analyse_logs_from_folder
        id: analyse_logs_from_folder
        if: always()
        uses: Superbasil3/build-failure-analyser-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          regexes-file-location: https://raw.githubusercontent.com/Superbasil3/build-failure-analyser-action/main/tests/build-failure-analyzer-causes.json
          path-log-file: ./tests/ressources/folder_with_logs/
  analyse_logs_from_file:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - name: analyse_logs_from_file
        id: analyse_logs_from_file
        if: always()
        uses: Superbasil3/build-failure-analyser-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          regexes-file-location: https://raw.githubusercontent.com/Superbasil3/build-failure-analyser-action/main/tests/build-failure-analyzer-causes.json
          path-log-file: ./tests/ressources/file_server.log
