on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:
  release-job:
    runs-on: ubuntu-latest
    name:
    steps:
      - name: Release
        run: |
          npm version minor -m "v%s"
          ncc build src/index.js -o dist/
          VERSION=$(node -p "require('./package.json').version")
          git tag ${VERSION}
