name: Pull Request Validation

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Try build-failure-analyser-action
    steps:
      - name: Create log file
        run: |
          echo 'This is a test' > ${RUNNER_TEMP}/logs.txt
          echo "${RUNNER_TEMP}/logs.txt"
          cat "${RUNNER_TEMP}/logs.txt"
      - id: generate_path_logs
        run: echo "::set-output name=path_logs::$(echo ${RUNNER_TEMP,,}'/logs.txt')"
      - name: Run test
        id: run
        uses: Superbasil3/build-failure-analyser-action@v0.3.3
        with:
          path-log-file: ${{ steps.generate_path_logs.outputs.path_logs }}
          github-token: 'TOTOT'
          github-database-repo: 'TATA'
