name: pr-validation
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  discussions: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: run_lint_on_build_failure_analyser_action
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: set_node.js_16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: install_ncc_modules
        run: npm install ncc
      - name: run_lint
        run: npm run lint
      - name: run_test
        run: npm run test
  integration-tests:
    runs-on: ubuntu-latest
    name: run_integration_test_on_build_failure_analyser_action
    steps:
      - id: generate_path_logs
        run: echo "path_logs=$(echo ${RUNNER_TEMP,,}'/logs.txt')" >> $GITHUB_OUTPUT
      - name: create_log_file
        run: |
          echo "# Logs sample taken from : https://www.ossec.net/docs/log_samples/apache/apache.html"  > ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "Fri Dec 16 01:46:23 2005] [error] [client 1.2.3.4] Directory index forbidden by rule: /home/test/"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Fri Dec 16 01:54:34 2005] [error] [client 1.2.3.4] Directory index forbidden by rule: /apache/web-data/test2"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Fri Dec 16 02:25:55 2005] [error] [client 1.2.3.4] Client sent malformed Host header"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Mon Dec 19 23:02:01 2005] [error] [client 1.2.3.4] user test: authentication failure for "/~dcid/test1": Password Mismatch"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "Apache error log (startup) 3 examples:¶"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "** Normal (v2.x)"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Sat Aug 12 04:05:51 2006] [notice] Apache/1.3.11 (Unix) mod_perl/1.21 configured -- resuming normal operations"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Thu Jun 22 14:20:55 2006] [notice] Digest: generating secret for digest authentication ..."  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Thu Jun 22 14:20:55 2006] [notice] Digest: done"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Thu Jun 22 14:20:55 2006] [notice] Apache/2.0.46 (Red Hat) DAV/2 configured -- resuming normal operations"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo ""  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "** Restart by HUP signal (optional suEXEC)"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Sat Aug 12 04:05:49 2006] [notice] SIGHUP received.  Attempting to restart"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Sat Aug 12 04:05:51 2006] [notice] suEXEC mechanism enabled (wrapper: /usr/local/apache/sbin/suexec)"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo ""  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "** after "unclean" shutdown (left over PID file)"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Sat Jun 24 09:06:22 2006] [warn] pid file /opt/CA/BrightStorARCserve/httpd/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Sat Jun 24 09:06:23 2006] [notice] Apache/2.0.46 (Red Hat) DAV/2 configured -- resuming normal operations(PATTERN_2_a)"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Sat Jun 24 09:06:22 2006] [notice] Digest: generating secret for digest authentication ..."  >> ${{ steps.generate_path_logs.outputs.path_logs }}
          echo "[Sat Jun 24 09:06:22 2006] [notice] Digest: done"  >> ${{ steps.generate_path_logs.outputs.path_logs }}
      - name: run_build_failure_analyser_action_local_file
        id: run_with_local_file
        uses: Superbasil3/build-failure-analyser-action@ISSUE-16
        with:
          path-log-file: ${{ steps.generate_path_logs.outputs.path_logs }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          regexes-file-location: ../regexes.json
